/*** Autogenerated by WIDL 5.16 from opccomn.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __opccomn_h__
#define __opccomn_h__

/* Forward declarations */

#ifndef __IOPCShutdown_FWD_DEFINED__
#define __IOPCShutdown_FWD_DEFINED__
typedef interface IOPCShutdown IOPCShutdown;
#ifdef __cplusplus
interface IOPCShutdown;
#endif /* __cplusplus */
#endif

#ifndef __IOPCCommon_FWD_DEFINED__
#define __IOPCCommon_FWD_DEFINED__
typedef interface IOPCCommon IOPCCommon;
#ifdef __cplusplus
interface IOPCCommon;
#endif /* __cplusplus */
#endif

#ifndef __IOPCServerList_FWD_DEFINED__
#define __IOPCServerList_FWD_DEFINED__
typedef interface IOPCServerList IOPCServerList;
#ifdef __cplusplus
interface IOPCServerList;
#endif /* __cplusplus */
#endif

#ifndef __IOPCEnumGUID_FWD_DEFINED__
#define __IOPCEnumGUID_FWD_DEFINED__
typedef interface IOPCEnumGUID IOPCEnumGUID;
#ifdef __cplusplus
interface IOPCEnumGUID;
#endif /* __cplusplus */
#endif

#ifndef __IOPCServerList2_FWD_DEFINED__
#define __IOPCServerList2_FWD_DEFINED__
typedef interface IOPCServerList2 IOPCServerList2;
#ifdef __cplusplus
interface IOPCServerList2;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <comcat.h>
#include <oaidl.h>
#include <ocidl.h>
#include <objidl.h>

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * IOPCShutdown interface
 */
#ifndef __IOPCShutdown_INTERFACE_DEFINED__
#define __IOPCShutdown_INTERFACE_DEFINED__

DEFINE_GUID(IID_IOPCShutdown, 0xf31dfde1, 0x07b6, 0x11d2, 0xb2,0xd8, 0x00,0x60,0x08,0x3b,0xa1,0xfb);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("f31dfde1-07b6-11d2-b2d8-0060083ba1fb")
IOPCShutdown : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE ShutdownRequest(
        LPCWSTR szReason) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IOPCShutdown, 0xf31dfde1, 0x07b6, 0x11d2, 0xb2,0xd8, 0x00,0x60,0x08,0x3b,0xa1,0xfb)
#endif
#else
typedef struct IOPCShutdownVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IOPCShutdown *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IOPCShutdown *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IOPCShutdown *This);

    /*** IOPCShutdown methods ***/
    HRESULT (STDMETHODCALLTYPE *ShutdownRequest)(
        IOPCShutdown *This,
        LPCWSTR szReason);

    END_INTERFACE
} IOPCShutdownVtbl;

interface IOPCShutdown {
    CONST_VTBL IOPCShutdownVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IOPCShutdown_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IOPCShutdown_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IOPCShutdown_Release(This) (This)->lpVtbl->Release(This)
/*** IOPCShutdown methods ***/
#define IOPCShutdown_ShutdownRequest(This,szReason) (This)->lpVtbl->ShutdownRequest(This,szReason)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IOPCShutdown_QueryInterface(IOPCShutdown* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IOPCShutdown_AddRef(IOPCShutdown* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IOPCShutdown_Release(IOPCShutdown* This) {
    return This->lpVtbl->Release(This);
}
/*** IOPCShutdown methods ***/
static FORCEINLINE HRESULT IOPCShutdown_ShutdownRequest(IOPCShutdown* This,LPCWSTR szReason) {
    return This->lpVtbl->ShutdownRequest(This,szReason);
}
#endif
#endif

#endif


#endif  /* __IOPCShutdown_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IOPCCommon interface
 */
#ifndef __IOPCCommon_INTERFACE_DEFINED__
#define __IOPCCommon_INTERFACE_DEFINED__

DEFINE_GUID(IID_IOPCCommon, 0xf31dfde2, 0x07b6, 0x11d2, 0xb2,0xd8, 0x00,0x60,0x08,0x3b,0xa1,0xfb);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("f31dfde2-07b6-11d2-b2d8-0060083ba1fb")
IOPCCommon : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE SetLocaleID(
        LCID dwLcid) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetLocaleID(
        LCID *pdwLcid) = 0;

    virtual HRESULT STDMETHODCALLTYPE QueryAvailableLocaleIDs(
        DWORD *pdwCount,
        LCID **pdwLcid) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetErrorString(
        HRESULT dwError,
        LPWSTR *ppString) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetClientName(
        LPCWSTR szName) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IOPCCommon, 0xf31dfde2, 0x07b6, 0x11d2, 0xb2,0xd8, 0x00,0x60,0x08,0x3b,0xa1,0xfb)
#endif
#else
typedef struct IOPCCommonVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IOPCCommon *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IOPCCommon *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IOPCCommon *This);

    /*** IOPCCommon methods ***/
    HRESULT (STDMETHODCALLTYPE *SetLocaleID)(
        IOPCCommon *This,
        LCID dwLcid);

    HRESULT (STDMETHODCALLTYPE *GetLocaleID)(
        IOPCCommon *This,
        LCID *pdwLcid);

    HRESULT (STDMETHODCALLTYPE *QueryAvailableLocaleIDs)(
        IOPCCommon *This,
        DWORD *pdwCount,
        LCID **pdwLcid);

    HRESULT (STDMETHODCALLTYPE *GetErrorString)(
        IOPCCommon *This,
        HRESULT dwError,
        LPWSTR *ppString);

    HRESULT (STDMETHODCALLTYPE *SetClientName)(
        IOPCCommon *This,
        LPCWSTR szName);

    END_INTERFACE
} IOPCCommonVtbl;

interface IOPCCommon {
    CONST_VTBL IOPCCommonVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IOPCCommon_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IOPCCommon_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IOPCCommon_Release(This) (This)->lpVtbl->Release(This)
/*** IOPCCommon methods ***/
#define IOPCCommon_SetLocaleID(This,dwLcid) (This)->lpVtbl->SetLocaleID(This,dwLcid)
#define IOPCCommon_GetLocaleID(This,pdwLcid) (This)->lpVtbl->GetLocaleID(This,pdwLcid)
#define IOPCCommon_QueryAvailableLocaleIDs(This,pdwCount,pdwLcid) (This)->lpVtbl->QueryAvailableLocaleIDs(This,pdwCount,pdwLcid)
#define IOPCCommon_GetErrorString(This,dwError,ppString) (This)->lpVtbl->GetErrorString(This,dwError,ppString)
#define IOPCCommon_SetClientName(This,szName) (This)->lpVtbl->SetClientName(This,szName)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IOPCCommon_QueryInterface(IOPCCommon* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IOPCCommon_AddRef(IOPCCommon* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IOPCCommon_Release(IOPCCommon* This) {
    return This->lpVtbl->Release(This);
}
/*** IOPCCommon methods ***/
static FORCEINLINE HRESULT IOPCCommon_SetLocaleID(IOPCCommon* This,LCID dwLcid) {
    return This->lpVtbl->SetLocaleID(This,dwLcid);
}
static FORCEINLINE HRESULT IOPCCommon_GetLocaleID(IOPCCommon* This,LCID *pdwLcid) {
    return This->lpVtbl->GetLocaleID(This,pdwLcid);
}
static FORCEINLINE HRESULT IOPCCommon_QueryAvailableLocaleIDs(IOPCCommon* This,DWORD *pdwCount,LCID **pdwLcid) {
    return This->lpVtbl->QueryAvailableLocaleIDs(This,pdwCount,pdwLcid);
}
static FORCEINLINE HRESULT IOPCCommon_GetErrorString(IOPCCommon* This,HRESULT dwError,LPWSTR *ppString) {
    return This->lpVtbl->GetErrorString(This,dwError,ppString);
}
static FORCEINLINE HRESULT IOPCCommon_SetClientName(IOPCCommon* This,LPCWSTR szName) {
    return This->lpVtbl->SetClientName(This,szName);
}
#endif
#endif

#endif


#endif  /* __IOPCCommon_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IOPCServerList interface
 */
#ifndef __IOPCServerList_INTERFACE_DEFINED__
#define __IOPCServerList_INTERFACE_DEFINED__

DEFINE_GUID(IID_IOPCServerList, 0x13486d50, 0x4821, 0x11d2, 0xa4,0x94, 0x3c,0xb3,0x06,0xc1,0x00,0x00);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("13486d50-4821-11d2-a494-3cb306c10000")
IOPCServerList : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE EnumClassesOfCategories(
        ULONG cImplemented,
        CATID rgcatidImpl[],
        ULONG cRequired,
        CATID rgcatidReq[],
        IEnumGUID **ppenumClsid) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetClassDetails(
        REFCLSID clsid,
        LPOLESTR *ppszProgID,
        LPOLESTR *ppszUserType) = 0;

    virtual HRESULT STDMETHODCALLTYPE CLSIDFromProgID(
        LPCOLESTR szProgId,
        LPCLSID clsid) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IOPCServerList, 0x13486d50, 0x4821, 0x11d2, 0xa4,0x94, 0x3c,0xb3,0x06,0xc1,0x00,0x00)
#endif
#else
typedef struct IOPCServerListVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IOPCServerList *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IOPCServerList *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IOPCServerList *This);

    /*** IOPCServerList methods ***/
    HRESULT (STDMETHODCALLTYPE *EnumClassesOfCategories)(
        IOPCServerList *This,
        ULONG cImplemented,
        CATID rgcatidImpl[],
        ULONG cRequired,
        CATID rgcatidReq[],
        IEnumGUID **ppenumClsid);

    HRESULT (STDMETHODCALLTYPE *GetClassDetails)(
        IOPCServerList *This,
        REFCLSID clsid,
        LPOLESTR *ppszProgID,
        LPOLESTR *ppszUserType);

    HRESULT (STDMETHODCALLTYPE *CLSIDFromProgID)(
        IOPCServerList *This,
        LPCOLESTR szProgId,
        LPCLSID clsid);

    END_INTERFACE
} IOPCServerListVtbl;

interface IOPCServerList {
    CONST_VTBL IOPCServerListVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IOPCServerList_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IOPCServerList_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IOPCServerList_Release(This) (This)->lpVtbl->Release(This)
/*** IOPCServerList methods ***/
#define IOPCServerList_EnumClassesOfCategories(This,cImplemented,rgcatidImpl,cRequired,rgcatidReq,ppenumClsid) (This)->lpVtbl->EnumClassesOfCategories(This,cImplemented,rgcatidImpl,cRequired,rgcatidReq,ppenumClsid)
#define IOPCServerList_GetClassDetails(This,clsid,ppszProgID,ppszUserType) (This)->lpVtbl->GetClassDetails(This,clsid,ppszProgID,ppszUserType)
#define IOPCServerList_CLSIDFromProgID(This,szProgId,clsid) (This)->lpVtbl->CLSIDFromProgID(This,szProgId,clsid)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IOPCServerList_QueryInterface(IOPCServerList* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IOPCServerList_AddRef(IOPCServerList* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IOPCServerList_Release(IOPCServerList* This) {
    return This->lpVtbl->Release(This);
}
/*** IOPCServerList methods ***/
static FORCEINLINE HRESULT IOPCServerList_EnumClassesOfCategories(IOPCServerList* This,ULONG cImplemented,CATID rgcatidImpl[],ULONG cRequired,CATID rgcatidReq[],IEnumGUID **ppenumClsid) {
    return This->lpVtbl->EnumClassesOfCategories(This,cImplemented,rgcatidImpl,cRequired,rgcatidReq,ppenumClsid);
}
static FORCEINLINE HRESULT IOPCServerList_GetClassDetails(IOPCServerList* This,REFCLSID clsid,LPOLESTR *ppszProgID,LPOLESTR *ppszUserType) {
    return This->lpVtbl->GetClassDetails(This,clsid,ppszProgID,ppszUserType);
}
static FORCEINLINE HRESULT IOPCServerList_CLSIDFromProgID(IOPCServerList* This,LPCOLESTR szProgId,LPCLSID clsid) {
    return This->lpVtbl->CLSIDFromProgID(This,szProgId,clsid);
}
#endif
#endif

#endif


#endif  /* __IOPCServerList_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IOPCEnumGUID interface
 */
#ifndef __IOPCEnumGUID_INTERFACE_DEFINED__
#define __IOPCEnumGUID_INTERFACE_DEFINED__

typedef IOPCEnumGUID *LPOPCENUMGUID;
DEFINE_GUID(IID_IOPCEnumGUID, 0x55c382c8, 0x21c7, 0x4e88, 0x96,0xc1, 0xbe,0xcf,0xb1,0xe3,0xf4,0x83);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("55c382c8-21c7-4e88-96c1-becfb1e3f483")
IOPCEnumGUID : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE Next(
        ULONG celt,
        GUID *rgelt,
        ULONG *pceltFetched) = 0;

    virtual HRESULT STDMETHODCALLTYPE Skip(
        ULONG celt) = 0;

    virtual HRESULT STDMETHODCALLTYPE Reset(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE Clone(
        IOPCEnumGUID **ppenum) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IOPCEnumGUID, 0x55c382c8, 0x21c7, 0x4e88, 0x96,0xc1, 0xbe,0xcf,0xb1,0xe3,0xf4,0x83)
#endif
#else
typedef struct IOPCEnumGUIDVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IOPCEnumGUID *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IOPCEnumGUID *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IOPCEnumGUID *This);

    /*** IOPCEnumGUID methods ***/
    HRESULT (STDMETHODCALLTYPE *Next)(
        IOPCEnumGUID *This,
        ULONG celt,
        GUID *rgelt,
        ULONG *pceltFetched);

    HRESULT (STDMETHODCALLTYPE *Skip)(
        IOPCEnumGUID *This,
        ULONG celt);

    HRESULT (STDMETHODCALLTYPE *Reset)(
        IOPCEnumGUID *This);

    HRESULT (STDMETHODCALLTYPE *Clone)(
        IOPCEnumGUID *This,
        IOPCEnumGUID **ppenum);

    END_INTERFACE
} IOPCEnumGUIDVtbl;

interface IOPCEnumGUID {
    CONST_VTBL IOPCEnumGUIDVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IOPCEnumGUID_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IOPCEnumGUID_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IOPCEnumGUID_Release(This) (This)->lpVtbl->Release(This)
/*** IOPCEnumGUID methods ***/
#define IOPCEnumGUID_Next(This,celt,rgelt,pceltFetched) (This)->lpVtbl->Next(This,celt,rgelt,pceltFetched)
#define IOPCEnumGUID_Skip(This,celt) (This)->lpVtbl->Skip(This,celt)
#define IOPCEnumGUID_Reset(This) (This)->lpVtbl->Reset(This)
#define IOPCEnumGUID_Clone(This,ppenum) (This)->lpVtbl->Clone(This,ppenum)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IOPCEnumGUID_QueryInterface(IOPCEnumGUID* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IOPCEnumGUID_AddRef(IOPCEnumGUID* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IOPCEnumGUID_Release(IOPCEnumGUID* This) {
    return This->lpVtbl->Release(This);
}
/*** IOPCEnumGUID methods ***/
static FORCEINLINE HRESULT IOPCEnumGUID_Next(IOPCEnumGUID* This,ULONG celt,GUID *rgelt,ULONG *pceltFetched) {
    return This->lpVtbl->Next(This,celt,rgelt,pceltFetched);
}
static FORCEINLINE HRESULT IOPCEnumGUID_Skip(IOPCEnumGUID* This,ULONG celt) {
    return This->lpVtbl->Skip(This,celt);
}
static FORCEINLINE HRESULT IOPCEnumGUID_Reset(IOPCEnumGUID* This) {
    return This->lpVtbl->Reset(This);
}
static FORCEINLINE HRESULT IOPCEnumGUID_Clone(IOPCEnumGUID* This,IOPCEnumGUID **ppenum) {
    return This->lpVtbl->Clone(This,ppenum);
}
#endif
#endif

#endif


#endif  /* __IOPCEnumGUID_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IOPCServerList2 interface
 */
#ifndef __IOPCServerList2_INTERFACE_DEFINED__
#define __IOPCServerList2_INTERFACE_DEFINED__

DEFINE_GUID(IID_IOPCServerList2, 0x9dd0b56c, 0xad9e, 0x43ee, 0x83,0x05, 0x48,0x7f,0x31,0x88,0xbf,0x7a);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("9dd0b56c-ad9e-43ee-8305-487f3188bf7a")
IOPCServerList2 : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE EnumClassesOfCategories(
        ULONG cImplemented,
        CATID rgcatidImpl[],
        ULONG cRequired,
        CATID rgcatidReq[],
        IOPCEnumGUID **ppenumClsid) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetClassDetails(
        REFCLSID clsid,
        LPOLESTR *ppszProgID,
        LPOLESTR *ppszUserType,
        LPOLESTR *ppszVerIndProgID) = 0;

    virtual HRESULT STDMETHODCALLTYPE CLSIDFromProgID(
        LPCOLESTR szProgId,
        LPCLSID clsid) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IOPCServerList2, 0x9dd0b56c, 0xad9e, 0x43ee, 0x83,0x05, 0x48,0x7f,0x31,0x88,0xbf,0x7a)
#endif
#else
typedef struct IOPCServerList2Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IOPCServerList2 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IOPCServerList2 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IOPCServerList2 *This);

    /*** IOPCServerList2 methods ***/
    HRESULT (STDMETHODCALLTYPE *EnumClassesOfCategories)(
        IOPCServerList2 *This,
        ULONG cImplemented,
        CATID rgcatidImpl[],
        ULONG cRequired,
        CATID rgcatidReq[],
        IOPCEnumGUID **ppenumClsid);

    HRESULT (STDMETHODCALLTYPE *GetClassDetails)(
        IOPCServerList2 *This,
        REFCLSID clsid,
        LPOLESTR *ppszProgID,
        LPOLESTR *ppszUserType,
        LPOLESTR *ppszVerIndProgID);

    HRESULT (STDMETHODCALLTYPE *CLSIDFromProgID)(
        IOPCServerList2 *This,
        LPCOLESTR szProgId,
        LPCLSID clsid);

    END_INTERFACE
} IOPCServerList2Vtbl;

interface IOPCServerList2 {
    CONST_VTBL IOPCServerList2Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IOPCServerList2_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IOPCServerList2_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IOPCServerList2_Release(This) (This)->lpVtbl->Release(This)
/*** IOPCServerList2 methods ***/
#define IOPCServerList2_EnumClassesOfCategories(This,cImplemented,rgcatidImpl,cRequired,rgcatidReq,ppenumClsid) (This)->lpVtbl->EnumClassesOfCategories(This,cImplemented,rgcatidImpl,cRequired,rgcatidReq,ppenumClsid)
#define IOPCServerList2_GetClassDetails(This,clsid,ppszProgID,ppszUserType,ppszVerIndProgID) (This)->lpVtbl->GetClassDetails(This,clsid,ppszProgID,ppszUserType,ppszVerIndProgID)
#define IOPCServerList2_CLSIDFromProgID(This,szProgId,clsid) (This)->lpVtbl->CLSIDFromProgID(This,szProgId,clsid)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IOPCServerList2_QueryInterface(IOPCServerList2* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IOPCServerList2_AddRef(IOPCServerList2* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IOPCServerList2_Release(IOPCServerList2* This) {
    return This->lpVtbl->Release(This);
}
/*** IOPCServerList2 methods ***/
static FORCEINLINE HRESULT IOPCServerList2_EnumClassesOfCategories(IOPCServerList2* This,ULONG cImplemented,CATID rgcatidImpl[],ULONG cRequired,CATID rgcatidReq[],IOPCEnumGUID **ppenumClsid) {
    return This->lpVtbl->EnumClassesOfCategories(This,cImplemented,rgcatidImpl,cRequired,rgcatidReq,ppenumClsid);
}
static FORCEINLINE HRESULT IOPCServerList2_GetClassDetails(IOPCServerList2* This,REFCLSID clsid,LPOLESTR *ppszProgID,LPOLESTR *ppszUserType,LPOLESTR *ppszVerIndProgID) {
    return This->lpVtbl->GetClassDetails(This,clsid,ppszProgID,ppszUserType,ppszVerIndProgID);
}
static FORCEINLINE HRESULT IOPCServerList2_CLSIDFromProgID(IOPCServerList2* This,LPCOLESTR szProgId,LPCLSID clsid) {
    return This->lpVtbl->CLSIDFromProgID(This,szProgId,clsid);
}
#endif
#endif

#endif


#endif  /* __IOPCServerList2_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __opccomn_h__ */
