/*** Autogenerated by WIDL 5.16 from opccomn.idl - Do not edit ***/

#include <rpc.h>
#include <rpcndr.h>

#ifdef _MIDL_USE_GUIDDEF_

#ifndef INITGUID
#define INITGUID
#include <guiddef.h>
#undef INITGUID
#else
#include <guiddef.h>
#endif

#define MIDL_DEFINE_GUID(type,name,l,w1,w2,b1,b2,b3,b4,b5,b6,b7,b8) \
    DEFINE_GUID(name,l,w1,w2,b1,b2,b3,b4,b5,b6,b7,b8)

#elif defined(__cplusplus)

#define MIDL_DEFINE_GUID(type,name,l,w1,w2,b1,b2,b3,b4,b5,b6,b7,b8) \
    EXTERN_C const type DECLSPEC_SELECTANY name = {l,w1,w2,{b1,b2,b3,b4,b5,b6,b7,b8}}

#else

#define MIDL_DEFINE_GUID(type,name,l,w1,w2,b1,b2,b3,b4,b5,b6,b7,b8) \
    const type DECLSPEC_SELECTANY name = {l,w1,w2,{b1,b2,b3,b4,b5,b6,b7,b8}}

#endif

#ifdef __cplusplus
extern "C" {
#endif

MIDL_DEFINE_GUID(IID, IID_IOPCShutdown, 0xf31dfde1, 0x07b6, 0x11d2, 0xb2,0xd8, 0x00,0x60,0x08,0x3b,0xa1,0xfb);
MIDL_DEFINE_GUID(IID, IID_IOPCCommon, 0xf31dfde2, 0x07b6, 0x11d2, 0xb2,0xd8, 0x00,0x60,0x08,0x3b,0xa1,0xfb);
MIDL_DEFINE_GUID(IID, IID_IOPCServerList, 0x13486d50, 0x4821, 0x11d2, 0xa4,0x94, 0x3c,0xb3,0x06,0xc1,0x00,0x00);
MIDL_DEFINE_GUID(IID, IID_IOPCEnumGUID, 0x55c382c8, 0x21c7, 0x4e88, 0x96,0xc1, 0xbe,0xcf,0xb1,0xe3,0xf4,0x83);
MIDL_DEFINE_GUID(IID, IID_IOPCServerList2, 0x9dd0b56c, 0xad9e, 0x43ee, 0x83,0x05, 0x48,0x7f,0x31,0x88,0xbf,0x7a);

#ifdef __cplusplus
}
#endif

#undef MIDL_DEFINE_GUID
