/*** Autogenerated by WIDL 5.16 from OpcEnum.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __opcenum_h__
#define __opcenum_h__

/* Forward declarations */

#ifndef __OpcServerList_FWD_DEFINED__
#define __OpcServerList_FWD_DEFINED__
#ifdef __cplusplus
typedef class OpcServerList OpcServerList;
#else
typedef struct OpcServerList OpcServerList;
#endif /* defined __cplusplus */
#endif /* defined __OpcServerList_FWD_DEFINED__ */

/* Headers for imported files */

#include <opccomn.h>

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * OpcServerList coclass
 */

DEFINE_GUID(CLSID_OpcServerList, 0x13486d51, 0x4821, 0x11d2, 0xa4,0x94, 0x3c,0xb3,0x06,0xc1,0x00,0x00);

#ifdef __cplusplus
class DECLSPEC_UUID("13486d51-4821-11d2-a494-3cb306c10000") OpcServerList;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(OpcServerList, 0x13486d51, 0x4821, 0x11d2, 0xa4,0x94, 0x3c,0xb3,0x06,0xc1,0x00,0x00)
#endif
#endif

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __opcenum_h__ */
